### ISSUE TITLE
Annotations missing for 'Quote' document

### ISSUE THREAD

**Issue by ngandriau** [marc0der/zim-service#2]
Hi Marco
I just watched a video of your [greach 2014 presentation](http://www.youtube.com/watch?v=UzDO-azDpd0)  about building Micro Services using Spring Boot...  

I liked it very much and I cloned this repo to play with the code.  
I was surprised to discover that the `zim.Quote` class has no annotation. I was expecting some [according to your presentation](http://marcovermeulen.github.io/spring-boot-groovy-talk/#/5/8) 

So I added them and then created some `Quote` documents in my `invasion` mongo database.  
But It was failing to find then using `curl`. Then I wonder how to specified the db  collections to use to put the `Quote` documents into and how to specify it within the code.  
In the end, I found the `@Document` annotation has a `collection` attribute.  
So I used it and created my documents into it.

Then everything worked perfectly.  
Is it the right way to do it, or do you recommend another way?

Thanks again for the presentation and for GVM ;-)

ps: here is my full version of the `zim.Quote` class:  

``` groovy
package zim

import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document
import org.springframework.data.mongodb.core.mapping.Field

@Document(collection = "quotes")
class Quote {
    @Id BigInteger id
    @Field String name
    @Field String message
}
```

**Comment by marc0der** [comment]
It's a great pleasure!

Regarding the annotations, they were in the presentation, but I subsequently discovered that Spring Data does not require them. It infers them from the name of your domain class. You also don't need the `@Id` and `@Field` annotations, once again it infers them by name.

One thing I could probably do is include a `.js` file that you can run on your mongodb to create the test data.

You can also see the [test fixtures](https://github.com/marcoVermeulen/zim-service/blob/master/src/testFunctional/steps/quote.groovy) to see how the data is created. You can run the full functional tests that runs an embedded mongodb by running:

```
./gradlew clean check
```

**Comment by ngandriau** [comment]
Thanks for the explanation Marco.  
I had not looked at the test fixtures. I have never played with cucumber, but I just started your other GREACH video.  

In the end, I never thought that springboot would use the name of the class `quote` as the name of the collection, which make perfect sense.

Adding a `.js` to support the import of some data would help and maybe an extra line of documentation in the `README.md`. But honestly is pretty straightforward, I should have guessed it.

Thanks again
